### PR TITLE
Update FileMigration.php

### PR DESCRIPTION
**Pull request by xepozz**
Using `exec` is a very very bad idea!

### CODE REVIEW

**Comment by schmunk42** [comment]
Why is `exec` in general a bad idea?

The issue with `file_get_contents` and using Yii and PHP for this instead of the native CLI command is that you might run into problems with large files (several 100s of MBs) and multiple commands.

**Comment by xepozz** [comment]
Because a mysql server may installed on remote server.
You may write drivers for it

**Comment by schmunk42** [comment]
The only way I could think about adding this feature is via a global flag and an `if/else` statement.

CC: @handcode @eluhr WDYT?

**Comment by handcode** [comment]
If mysql server is installed on remote i can see no problem. This is our default setup ;-)
But of course exec 'mysql' from PHP can be a problem if the mysql **client** is not installed locally.

Apart from that i also think file_get_contents with large dumps is not a good idea.

So I  agree with @schmunk42 : it can only be implemented as a configurable alternative to execCommand.

**Comment by xepozz** [comment]
I'm ready to complete this PR :smile: 
https://github.com/dmstr/yii2-db/pull/27

**Pull request closed without merging**
