### PR TITLE
MySQL 8.0 changed GRANT

### PR DESCRIPTION
**Pull request by tibee**
ERROR 1410 (42000): You are not allowed to create a user with GRANT

https://stackoverflow.com/questions/50177216/how-to-grant-all-privileges-to-root-user-in-mysql-8-0

### CODE REVIEW

**Comment by schmunk42** [comment]
@tibee Is this also compatible with Mysql 5.x?

**Comment by tibee** [comment]
@schmunk42 of course, tested with 5.7.25-28

> @tibee Is this also compatible with Mysql 5.x?

**Comment by schmunk42** [comment]
Thank you!

**Comment by schmunk42** [comment]
Looks like this breaks at least on `percona:5.6`, but we'll leave it as is.

**Pull request merged**
